---
ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
          - ".github/*.yml"
          - ".yamllint.yaml"
          - ".pre-commit-config.yaml"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - "docs/**"
          - "**/README.md"
          - "**/CONTRIBUTING.md"

meta:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - ".gitignore"
          - ".gitattributes"
          - ".editorconfig"
          - ".tool-versions"
          - ".envrc"

stack:
  - changed-files:
      - any-glob-to-any-file:
          - "stack/**"
          - "docker-compose*.yml"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "Dockerfile"
          - "**/Dockerfile"
          - "stack/**/*.env"
          - "stack/**/*.dockerfile"

config:
  - changed-files:
      - any-glob-to-any-file:
          - ".env"
          - ".env.*"
          - "stack/.env"
          - "stack/.env.*"
          - "Makefile"
          - "justfile"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "requirements.txt"
          - "poetry.lock"
          - "pyproject.toml"
          - "stack/**/Dockerfile"
          - "**/package*.json"
